"""added pic url in user and transaction

Revision ID: 2c7c55cde59d
Revises: a624c0208d3d
Create Date: 2022-11-11 15:51:55.171059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7c55cde59d'
down_revision = 'a624c0208d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_pic_url', sa.String(length=512), server_default='', nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=512), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('transactions', 'transaction_pic_url')
    # ### end Alembic commands ###
