"""add fname income expense and settings in users table

Revision ID: a624c0208d3d
Revises: de772e57d1f1
Create Date: 2022-10-26 00:20:58.946579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a624c0208d3d'
down_revision = 'de772e57d1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=32), server_default='Full Name', nullable=False))
    op.add_column('users', sa.Column('total_income', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_expense', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=2), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'total_expense')
    op.drop_column('users', 'total_income')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
